---
- hosts: appserver
  tasks:
    - name: copy docker-compose
      copy: src=../docker-compose.yml dest=/home/ubuntu/app/ 
      
    - name: deploy docker-compose 
      command: docker-compose up -d --force-recreate
      args:
        chdir: /home/ubuntu/app/ 
      
      
